// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAOcmvCwm9Suk132WWJIECuSeeDyGYfqs',
    appId: '1:377430239166:web:3d05b6132654ffa62b3bef',
    messagingSenderId: '377430239166',
    projectId: 'bottle-f89fd',
    authDomain: 'bottle-f89fd.firebaseapp.com',
    storageBucket: 'bottle-f89fd.appspot.com',
    measurementId: 'G-T2HXM0Z99Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6mZT-b51nPe6JSbPZxB9SVil8tyOAfMU',
    appId: '1:377430239166:android:2cf7685b9ea082b22b3bef',
    messagingSenderId: '377430239166',
    projectId: 'bottle-f89fd',
    storageBucket: 'bottle-f89fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFfFEuNjxrhFSNGKJFM4lzSMqtVqIoEWY',
    appId: '1:377430239166:ios:b04b8664fe690af12b3bef',
    messagingSenderId: '377430239166',
    projectId: 'bottle-f89fd',
    storageBucket: 'bottle-f89fd.appspot.com',
    iosBundleId: 'com.example.bottleVer2',
  );
}
